name: publish

on: 
  push:
    branches:
      - main
      - devel

jobs:
  publish-rhomis-api-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to the container registry
    uses: docker/login-action@v1
    with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the api image
      run: |
        docker build . --tag ghcr.io/lgorman/rhomis-api:latest
        docker run -p 3001:3001 ghcr.io/lgorman/rhomis-api:latest
        docker push ghcr.io/lgorman/rhomis-api:latest
