name: publish

on:
  push:
    branches:
      - main
      - devel

jobs:
  publish-rhomis-api-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build the api image
        run: |
          docker build . --tag ghcr.io/lgorman/rhomis-api:latest
          docker run -p 3001:3001 ghcr.io/lgorman/rhomis-api:latest
          docker push ghcr.io/lgorman/rhomis-api:latest
